# Generated by Django 2.0.1 on 2018-01-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
